name: Start

on: 
  workflow_dispatch:
    inputs:
      link_iso:
        description: 'dán link iso của ae vô đây'
        required: true
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chuẩn bị phần mềm
        run: |
          sudo apt update -y
          sudo apt install wget curl -y
          wget -O ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -zxvf ngrok.tgz
          ./ngrok config add-authtoken 2caMIyH98jojFijfUDA9HHKZDZ0_2naziucGo1SjGJ4xWL8QM
          ./ngrok http 8006 &>/dev/null &
      - name: Cài win và khởi chạy(lấy website novnc tại đây)
        run: |
          sudo chmod 666 /dev/kvm
          sudo mkdir /isos/
          sudo wget -O /isos/a.iso "${{ github.event.inputs.link_iso }}" &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          sudo wget -O /isos/driver.iso https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.240-1/virtio-win-0.1.240.iso &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          wget https://raw.githubusercontent.com/RyuiMinh/ActionDocker/main/compose.yaml &>/dev/null &
          echo "Đã kết nối thành công với cổng 8006"
          curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"https:..([^"]*).*/\1/p'
          sudo docker compose up &>/dev/null &
